# Completed Course Info

alfheim_easy = {
    "name": "Alfheim",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":2,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":57,
    "front_nine_par":27,
    "back_nine_par":30,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

alfheim_hard = {
    "name": "Alfheim",
    "hole_1_par":5,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":61,
    "difficulty": "Hard", 
    "front_nine_par": 32, 
    "back_nine_par": 29,
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

arizona_modern_easy = {
    "name": "Arizona Modern",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":4,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":5,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":4,
    "hole_12_par":5,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":66,
    "difficulty": "Easy", 
    "front_nine_par": 33, 
    "back_nine_par": 33,
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

arizona_modern_hard = {
    "name": "Arizona Modern",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":5,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":4,
    "hole_12_par":5,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":65,
    "front_nine_par": 32, 
    "back_nine_par": 33, 
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

around_the_world_in_80_days_easy = {
    "name": "Around The World In 80 Days",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":57,
    "front_nine_par": 30, 
    "back_nine_par": 27, 
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

around_the_world_in_80_days_hard = {
    "name": "Around The World In 80 Days",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":2,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":56,
    "front_nine_par": 28, 
    "back_nine_par": 28,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

atlantis_easy = {
    "name": "Atlantis",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":59,
    "difficulty": "Easy", 
    "front_nine_par": 29,
    "back_nine_par": 30,
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

atlantis_hard = {
    "name": "Atlantis",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":2,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":59,
    "difficulty": "Hard", 
    "front_nine_par": 27,
    "back_nine_par": 32,
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

bogeys_bonanza_easy = {
    "name": "Bogey's Bonanza",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":2,
    "hole_12_par":4,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":60,
    "front_nine_par": 31,
    "back_nine_par": 29,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

bogeys_bonanza_hard = {
    "name": "Bogey's Bonanza",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":5,
    "hole_4_par":4,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":2,
    "hole_12_par":5,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":5,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":6,
    "total_par":67,
    "front_nine_par": 33,
    "back_nine_par": 34,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

center_of_the_earth_easy = {
    "name": "Journey To The Center Of The Earth",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":56,
    "front_nine_par": 27,
    "back_nine_par": 29,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

center_of_the_earth_hard = {
    "name": "Journey To The Center Of The Earth",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":60,
    "front_nine_par": 30,
    "back_nine_par": 30,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

cherry_blossom_easy = {
    "name": "Cherry Blossom",
    "hole_1_par":3,
    "hole_2_par":4,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":5,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":2,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":7,
    "total_par":63,
    "front_nine_par": 30,
    "back_nine_par": 33,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

cherry_blossom_hard = {
    "name": "Cherry Blossom",
    "hole_1_par":3,
    "hole_2_par":4,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":8,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":2,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":4,
    "hole_18_par":6,
    "total_par":67,
    "front_nine_par": 31,
    "back_nine_par": 30,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

el_dorado_easy = {
    "name": "El Dorado",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":5,
    "hole_10_par":3,
    "hole_11_par":5,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":62,
    "front_nine_par": 30,
    "back_nine_par": 32,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

el_dorado_hard = {
    "name": "El Dorado",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":5,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":61,
    "front_nine_par": 31,
    "back_nine_par": 30,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

gardens_of_babylon_easy = {
    "name": "Gardens Of Babylon",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":5,
    "hole_7_par":2,
    "hole_8_par":3,
    "hole_9_par":6,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":61,
    "front_nine_par": 31,
    "back_nine_par": 30,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

gardens_of_babylon_hard = {
    "name": "Gardens Of Babylon",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":6,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":4,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":4,
    "hole_18_par":4,
    "total_par":64,
    "front_nine_par": 32,
    "back_nine_par": 32,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

ice_lair_easy = {
    "name": "Ice Lair",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":5,
    "hole_17_par":4,
    "hole_18_par":4,
    "total_par":61,
    "front_nine_par": 28,
    "back_nine_par": 33,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

ice_lair_hard = {
    "name": "Ice Lair",
    "hole_1_par":3,
    "hole_2_par":2,
    "hole_3_par":2,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":5,
    "hole_17_par":4,
    "hole_18_par":4,
    "total_par":59,
    "front_nine_par": 26,
    "back_nine_par": 33,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

labyrinth_easy = {
    "name": "Labyrinth",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":5,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":6,
    "total_par":64,
    "front_nine_par": 32,
    "back_nine_par": 32,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

labyrinth_hard = {
    "name": "Labyrinth",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":5,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":5,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":5,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":4,
    "hole_18_par":4,
    "total_par":65,
    "front_nine_par": 32,
    "back_nine_par": 33,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

laser_lair_easy = {
    "name": "Laser Lair",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":2,
    "total_par":57,
    "front_nine_par": 28,
    "back_nine_par": 29,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

laser_lair_hard = {
    "name": "Laser Lair",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":58,
    "front_nine_par": 29,
    "back_nine_par": 29,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

meow_wolf_easy = {
    "name": "Meow Wolf",
    "hole_1_par":3,
    "hole_2_par":2,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":4,
    "hole_18_par":2,
    "total_par":57,
    "front_nine_par": 29,
    "back_nine_par": 28,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

meow_wolf_hard = {
    "name": "Meow Wolf",
    "hole_1_par":3,
    "hole_2_par":2,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":2,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":2,
    "hole_12_par":5,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":5,
    "hole_17_par":4,
    "hole_18_par":2,
    "total_par":57,
    "front_nine_par": 26,
    "back_nine_par": 31,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

myst_easy = {
    "name": "Myst",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":4,
    "hole_18_par":4,
    "total_par":61,
    "front_nine_par": 30,
    "back_nine_par": 31,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

myst_hard = {
    "name": "Myst",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":5,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":4,
    "hole_18_par":5,
    "total_par":63,
    "front_nine_par": 30,
    "back_nine_par": 33,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

original_gothic_easy = {
    "name": "Original Gothic",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":2,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":2,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":4,
    "hole_18_par":3,
    "total_par":54,
    "front_nine_par": 24,
    "back_nine_par": 30,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

original_gothic_hard = {
    "name": "Original Gothic",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":5,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":5,
    "hole_18_par":4,
    "total_par":64,
    "front_nine_par": 29,
    "back_nine_par": 35,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

quixote_valley_easy = {
    "name": "Quixote Valley",
    "hole_1_par":2,
    "hole_2_par":2,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":2,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":54,
    "front_nine_par": 26,
    "back_nine_par": 28,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

quixote_valley_hard = {
    "name": "Quixote Valley",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":5,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":60,
    "front_nine_par": 30,
    "back_nine_par": 30,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

seagull_stacks_easy = {
    "name": "Seagull Stacks",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":2,
    "hole_6_par":5,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":5,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":62,
    "front_nine_par": 29,
    "back_nine_par": 33,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

seagull_stacks_hard = {
    "name": "Seagull Stacks",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":5,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":5,
    "hole_14_par":3,
    "hole_15_par":5,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":67,
    "front_nine_par": 32,
    "back_nine_par": 35,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

shangri_la_easy = {
    "name": "Shangri La",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":5,
    "hole_13_par":3,
    "hole_14_par":5,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":64,
    "front_nine_par": 29,
    "back_nine_par": 35,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

shangri_la_hard = {
    "name": "Shangri La",
    "hole_1_par":4,
    "hole_2_par":4,
    "hole_3_par":2,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":4,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":5,
    "hole_15_par":5,
    "hole_16_par":3,
    "hole_17_par":4,
    "hole_18_par":6,
    "total_par":68,
    "front_nine_par": 32,
    "back_nine_par": 36,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

sweetopia_easy = {
    "name": "Sweetopia",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":2,
    "hole_7_par":4,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":2,
    "hole_18_par":4,
    "total_par":55,
    "front_nine_par": 28,
    "back_nine_par": 27,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

sweetopia_hard = {
    "name": "Sweetopia",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":2,
    "hole_15_par":4,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":59,
    "front_nine_par": 30,
    "back_nine_par": 29,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

temple_at_zerzura_easy = {
    "name": "Temple At Zerzura",
    "hole_1_par":3,
    "hole_2_par":4,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":5,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":5,
    "total_par":63,
    "front_nine_par": 32,
    "back_nine_par": 31,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

temple_at_zerzura_hard = {
    "name": "Temple At Zerzura",
    "hole_1_par":4,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":5,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":2,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":60,
    "front_nine_par": 32,
    "back_nine_par": 28,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

tethys_station_easy = {
    "name": "Tethys Station",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":4,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":5,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":4,
    "hole_17_par":5,
    "hole_18_par":4,
    "total_par":63,
    "front_nine_par": 30,
    "back_nine_par": 33,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

tethys_station_hard = {
    "name": "Tethys Station",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":4,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":5,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":4,
    "hole_17_par":5,
    "hole_18_par":4,
    "total_par":64,
    "front_nine_par": 32,
    "back_nine_par": 32,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

tourist_trap_easy = {
    "name": "Tourist Trap",
    "hole_1_par":2,
    "hole_2_par":2,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":3,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":6,
    "total_par":57,
    "front_nine_par": 26,
    "back_nine_par": 31,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

tourist_trap_hard = {
    "name": "Tourist Trap",
    "hole_1_par":2,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":6,
    "total_par":61,
    "front_nine_par": 28,
    "back_nine_par": 33,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

twenty_thousand_leagues_under_the_sea_easy = {
    "name": "20,000 Leagues Under The Sea",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":3,
    "total_par":59,
    "front_nine_par": 29,
    "back_nine_par": 30,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

twenty_thousand_leagues_under_the_sea_hard = {
    "name": "20,000 Leagues Under The Sea",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":3,
    "hole_7_par":4,
    "hole_8_par":4,
    "hole_9_par":3,
    "hole_10_par":4,
    "hole_11_par":3,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":3,
    "hole_15_par":4,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":60,
    "front_nine_par": 29,
    "back_nine_par": 31,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

venice_easy = {
    "name": "Venice",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":4,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":3,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":58,
    "front_nine_par": 29,
    "back_nine_par": 29,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

venice_hard = {
    "name": "Venice",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":3,
    "hole_6_par":5,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":3,
    "hole_10_par":3,
    "hole_11_par":3,
    "hole_12_par":4,
    "hole_13_par":3,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":3,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":60,
    "front_nine_par": 30,
    "back_nine_par": 30,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

widows_walkabout_easy = {
    "name": "Widow's Walkabout",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":4,
    "hole_7_par":3,
    "hole_8_par":3,
    "hole_9_par":5,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":3,
    "hole_16_par":2,
    "hole_17_par":3,
    "hole_18_par":4,
    "total_par":61,
    "front_nine_par": 31,
    "back_nine_par": 30,
    "difficulty": "Easy", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}

widows_walkabout_hard = {
    "name": "Widow's Walkabout",
    "hole_1_par":3,
    "hole_2_par":3,
    "hole_3_par":3,
    "hole_4_par":3,
    "hole_5_par":4,
    "hole_6_par":4,
    "hole_7_par":4,
    "hole_8_par":3,
    "hole_9_par":4,
    "hole_10_par":3,
    "hole_11_par":4,
    "hole_12_par":3,
    "hole_13_par":4,
    "hole_14_par":4,
    "hole_15_par":2,
    "hole_16_par":2,
    "hole_17_par":4,
    "hole_18_par":3,
    "total_par":60,
    "front_nine_par": 31,
    "back_nine_par": 29,
    "difficulty": "Hard", 
    "game": "Walkabout Mini Golf",
    "type": "VR"
}


all_courses = [alfheim_easy, alfheim_hard, arizona_modern_easy,arizona_modern_hard, around_the_world_in_80_days_easy, around_the_world_in_80_days_hard, atlantis_easy, atlantis_hard,
               bogeys_bonanza_easy, bogeys_bonanza_hard, center_of_the_earth_easy, center_of_the_earth_hard, cherry_blossom_easy, cherry_blossom_hard, el_dorado_easy, el_dorado_hard,
               gardens_of_babylon_easy, gardens_of_babylon_hard, ice_lair_easy, ice_lair_hard, labyrinth_easy, labyrinth_hard, laser_lair_easy, laser_lair_hard, meow_wolf_easy, meow_wolf_hard, myst_easy, myst_hard,
               original_gothic_easy, original_gothic_hard, quixote_valley_easy, quixote_valley_hard, seagull_stacks_easy, seagull_stacks_hard, shangri_la_easy, shangri_la_hard,
               sweetopia_easy, sweetopia_hard, temple_at_zerzura_easy, temple_at_zerzura_hard, tethys_station_easy, tethys_station_hard, tourist_trap_easy, tourist_trap_hard, 
               twenty_thousand_leagues_under_the_sea_easy, twenty_thousand_leagues_under_the_sea_hard, venice_easy, venice_hard, widows_walkabout_easy, widows_walkabout_hard]






def test_par_accuracy(course_lst: list):
    parSum = 0

    for course in course_lst:
        for hole, value in course.items():
            if "hole_" in hole:
                parSum += value
    
        if parSum == course["total_par"]:
            print("Success!", course["name"], course["difficulty"], parSum, course["total_par"])
        
        if parSum != course["total_par"]: 
            print("Failure", course["name"], course["difficulty"], parSum, course["total_par"])
        parSum = 0

def back_and_front_nine_test(course_lst: list):
    
    for course in course_lst:
        front_nine = course["hole_1_par"] + course["hole_2_par"] + course["hole_3_par"] + course["hole_4_par"] + course["hole_5_par"] + course["hole_6_par"] + course["hole_7_par"] + course["hole_8_par"] + course["hole_9_par"]
        back_nine = course["hole_10_par"] + course["hole_11_par"] + course["hole_12_par"] + course["hole_13_par"] + course["hole_14_par"] + course["hole_15_par"] + course["hole_16_par"] + course["hole_17_par"] + course["hole_18_par"]
       
        if front_nine + back_nine == course["total_par"]:
            print(f"""{course["name"]}: {course["difficulty"]}. 
                  "front_nine_par": {front_nine}, 
                  "back_nine_par": {back_nine},"""
                  
                  )
        elif front_nine + back_nine != course["total_par"]:
            print("ERROR", course["name"], course["difficulty"], "Mismatch Between Front And Back 9 Pars: ", front_nine + back_nine, course["total_par"])


def test_VR_accuracy(course_lst: list):
    for course in course_lst:
        if "type" not in course.keys():
            print("Failure")



#back_and_front_nine_test(all_courses)
#test_par_accuracy(all_courses)
test_VR_accuracy(all_courses)